### ISSUE TITLE
Button Text (ie. paper-button instead of paper-icon-button)

### ISSUE THREAD

**Issue by bennypowers** [PolymerElements/paper-swatch-picker#11]
### Description

Please allow the user of `paper-button` instead of hard-coding `paper-icon-button`

**Comment by bennyp123** [comment]
see https://github.com/PolymerElements/paper-swatch-picker/pull/14

**Comment by rene-lindner-isw** [comment]
How about completly remove the overlay function and let the users build them themself they way the want it?

```
<paper-menu-button>
  <paper-icon-button slot="dropdown-trigger"></paper-icon-button>
  <paper-swatch-picker></paper-swatch-picker>
</paper-menu-button>
```

```
<paper-menu-button>
  <paper-input slot="dropdown-trigger"></paper-input>
  <paper-swatch-picker></paper-swatch-picker>
</paper-menu-button>
```

```
<paper-dialog>
  <paper-swatch-picker></paper-swatch-picker>
</paper-dialog>
```

**Comment by jsilvermist** [comment]
+1 to the outsource option, though I don't think the current functionality should be changed.

**Comment by rene-lindner-isw** [comment]
@notwaldorf what to you think to the outsource option? Would an PR implementing this be considered?

**Comment by rene-lindner-isw** [comment]
JFYI: I've build for our app an picker bundled with an input field.
https://www.webcomponents.org/element/IswPolymerElements/isw-color-input

For the functionality i've forked the swatch picker, copied the picker to paper-swatch-picker-content and removed the overlay functionality. Since i don't need the original picker i have not updated the original paper-swatch-picker to use the content element, but i could add it if there's any interest to merge this.

https://github.com/IswPolymerElements/paper-swatch-picker

**Comment by notwaldorf** [comment]
I really wanted to keep this element as simple as possible. There's a PR open to be able to replace the icon, which is good, but completely rewriting this element is not something I plan on doing :(

**Comment by rene-lindner-isw** [comment]
What i suggested is to outsource the overlay content to an separate element and update the `paper-swatch-picker` to use it. So the API of the `paper-swatch-picker` would not change.

And i could provide an PR for this, since i already forked and implemented this for our input field.

**Comment by davidmaxwaterman** [comment]
@notwaldorf did you reconsider this based on the most recent comment?
